/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertIcon: typeof import('./components/AlertIcon.vue')['default']
    Breadcrumbs: typeof import('./components/user/breadcrumbs.vue')['default']
    ChangeLang: typeof import('./components/changeLang.vue')['default']
    CustomLogo: typeof import('./components/CustomLogo.vue')['default']
    ExtraBox: typeof import('./components/vertical-sidebar/extrabox/ExtraBox.vue')['default']
    Icons: typeof import('./components/icons.vue')['default']
    IconSet: typeof import('./components/vertical-sidebar/IconSet.vue')['default']
    LoadingMsg: typeof import('./components/loadingMsg.vue')['default']
    NavCollapse: typeof import('./components/vertical-sidebar/NavCollapse/NavCollapse.vue')['default']
    NavGroup: typeof import('./components/vertical-sidebar/NavGroup/NavGroup.vue')['default']
    NavItem: typeof import('./components/vertical-sidebar/NavItem/NavItem.vue')['default']
    PageSlider: typeof import('./components/user/pageSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareApp: typeof import('./components/shareApp.vue')['default']
    UserPage: typeof import('./components/user/userPage.vue')['default']
    UsersUpdate: typeof import('./components/user/usersUpdate.vue')['default']
    VerticalSidebar: typeof import('./components/vertical-sidebar/VerticalSidebar.vue')['default']
  }
}
