/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/test': RouteRecordInfo<'/auth/test', '/auth/test', Record<never, never>, Record<never, never>>,
    '/auth/token': RouteRecordInfo<'/auth/token', '/auth/token', Record<never, never>, Record<never, never>>,
    '/error/login': RouteRecordInfo<'/error/login', '/error/login', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
    '/user/components/dutytable/item': RouteRecordInfo<'/user/components/dutytable/item', '/user/components/dutytable/item', Record<never, never>, Record<never, never>>,
    '/user/components/newsletter': RouteRecordInfo<'/user/components/newsletter', '/user/components/newsletter', Record<never, never>, Record<never, never>>,
    '/user/components/qr': RouteRecordInfo<'/user/components/qr', '/user/components/qr', Record<never, never>, Record<never, never>>,
    '/user/components/sideNav': RouteRecordInfo<'/user/components/sideNav', '/user/components/sideNav', Record<never, never>, Record<never, never>>,
    '/user/dashboard': RouteRecordInfo<'/user/dashboard', '/user/dashboard', Record<never, never>, Record<never, never>>,
    '/user/dutyTable': RouteRecordInfo<'/user/dutyTable', '/user/dutyTable', Record<never, never>, Record<never, never>>,
    '/user/EBusinessCard': RouteRecordInfo<'/user/EBusinessCard', '/user/EBusinessCard', Record<never, never>, Record<never, never>>,
    '/user/home': RouteRecordInfo<'/user/home', '/user/home', Record<never, never>, Record<never, never>>,
    '/user/hr/hrdocuments': RouteRecordInfo<'/user/hr/hrdocuments', '/user/hr/hrdocuments', Record<never, never>, Record<never, never>>,
    '/user/hr/HRServiceDisk': RouteRecordInfo<'/user/hr/HRServiceDisk', '/user/hr/HRServiceDisk', Record<never, never>, Record<never, never>>,
    '/user/hr/Internalvacancies': RouteRecordInfo<'/user/hr/Internalvacancies', '/user/hr/Internalvacancies', Record<never, never>, Record<never, never>>,
    '/user/lrtdrivers': RouteRecordInfo<'/user/lrtdrivers', '/user/lrtdrivers', Record<never, never>, Record<never, never>>,
    '/user/newsletters/addnewsletters': RouteRecordInfo<'/user/newsletters/addnewsletters', '/user/newsletters/addnewsletters', Record<never, never>, Record<never, never>>,
    '/user/newsletters/newsletters': RouteRecordInfo<'/user/newsletters/newsletters', '/user/newsletters/newsletters', Record<never, never>, Record<never, never>>,
    '/user/operations/lrt/dutyTable/admin': RouteRecordInfo<'/user/operations/lrt/dutyTable/admin', '/user/operations/lrt/dutyTable/admin', Record<never, never>, Record<never, never>>,
    '/user/operations/lrt/dutyTable/components/dutyUsers': RouteRecordInfo<'/user/operations/lrt/dutyTable/components/dutyUsers', '/user/operations/lrt/dutyTable/components/dutyUsers', Record<never, never>, Record<never, never>>,
    '/user/operations/lrt/dutyTable/components/newDutyTable': RouteRecordInfo<'/user/operations/lrt/dutyTable/components/newDutyTable', '/user/operations/lrt/dutyTable/components/newDutyTable', Record<never, never>, Record<never, never>>,
    '/user/operations/lrt/dutyTable/components/tables': RouteRecordInfo<'/user/operations/lrt/dutyTable/components/tables', '/user/operations/lrt/dutyTable/components/tables', Record<never, never>, Record<never, never>>,
    '/user/operations/lrt/dutyTable/selectedTable': RouteRecordInfo<'/user/operations/lrt/dutyTable/selectedTable', '/user/operations/lrt/dutyTable/selectedTable', Record<never, never>, Record<never, never>>,
    '/user/operations/lrt/dutyTable/view': RouteRecordInfo<'/user/operations/lrt/dutyTable/view', '/user/operations/lrt/dutyTable/view', Record<never, never>, Record<never, never>>,
    '/user/policies/': RouteRecordInfo<'/user/policies/', '/user/policies', Record<never, never>, Record<never, never>>,
    '/user/policies/document': RouteRecordInfo<'/user/policies/document', '/user/policies/document', Record<never, never>, Record<never, never>>,
    '/user/safeMode/home': RouteRecordInfo<'/user/safeMode/home', '/user/safeMode/home', Record<never, never>, Record<never, never>>,
    '/user/shareyourvoice': RouteRecordInfo<'/user/shareyourvoice', '/user/shareyourvoice', Record<never, never>, Record<never, never>>,
    '/user/system/admin/admin': RouteRecordInfo<'/user/system/admin/admin', '/user/system/admin/admin', Record<never, never>, Record<never, never>>,
    '/user/system/admin/training': RouteRecordInfo<'/user/system/admin/training', '/user/system/admin/training', Record<never, never>, Record<never, never>>,
    '/user/trainingCenter/AddTraining': RouteRecordInfo<'/user/trainingCenter/AddTraining', '/user/trainingCenter/AddTraining', Record<never, never>, Record<never, never>>,
    '/user/trainingCenter/components/trainings': RouteRecordInfo<'/user/trainingCenter/components/trainings', '/user/trainingCenter/components/trainings', Record<never, never>, Record<never, never>>,
    '/user/trainingCenter/components/trainingUsers': RouteRecordInfo<'/user/trainingCenter/components/trainingUsers', '/user/trainingCenter/components/trainingUsers', Record<never, never>, Record<never, never>>,
    '/user/trainingCenter/components/tree': RouteRecordInfo<'/user/trainingCenter/components/tree', '/user/trainingCenter/components/tree', Record<never, never>, Record<never, never>>,
    '/user/trainingCenter/TrainingCenter': RouteRecordInfo<'/user/trainingCenter/TrainingCenter', '/user/trainingCenter/TrainingCenter', Record<never, never>, Record<never, never>>,
    '/user/trainingCenter/ViewTraining': RouteRecordInfo<'/user/trainingCenter/ViewTraining', '/user/trainingCenter/ViewTraining', Record<never, never>, Record<never, never>>,
    '/user/trainingCenter/ViewTraining copy': RouteRecordInfo<'/user/trainingCenter/ViewTraining copy', '/user/trainingCenter/ViewTraining copy', Record<never, never>, Record<never, never>>,
    '/user/xlstojson': RouteRecordInfo<'/user/xlstojson', '/user/xlstojson', Record<never, never>, Record<never, never>>,
  }
}
